apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockExternalServices
metadata:
  name: block-external-services
spec:
  match:
    excludedNamespaces:
      - ingress-nginx
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
